routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\QuoteordersController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\JobsController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\QuotesController;
use App\Http\Controllers\PhoneMessageController;
use App\Http\Controllers\ContactsController;
use App\Http\Controllers\AdministrationController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\DownloadsController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\AjaxController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PassresetController;
use App\Http\Controllers\DoorGalleryController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\CatalogCategoryController;
use App\Http\Controllers\ToolController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\PricerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/price-checker', [PricerController::class, 'index']);
Route::get('/price-checker/{jobID}/{code}/{finishedinterior}/{finishedends}', [PricerController::class, 'getItemPrice']);

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware('auth');
Route::get('/dashboard/index', [DashboardController::class, 'index'])->name('dashboard');

Route::get('/quote_orders', [QuoteordersController::class, 'index']);
Route::post('/job', [ApplicationController::class, 'index']); 

Route::post('quote_orders/file_upload', [QuoteordersController::class, 'fileupload']);
Route::get('quote_orders/summary/{jobID}', [QuoteordersController::class, 'summary'])->name('quote_orders.summary');
Route::get('quote_orders/summaryPdf/{jobID}', [QuoteordersController::class, 'summaryPdf'])->name('quote_orders.pdf');
Route::post('quote_orders/summaryPdf/{jobID}', [QuoteordersController::class, 'summaryPdf']);
Route::post('quote_orders/store', [QuoteordersController::class, 'store']);
Route::get('/quote_orders/generalnotes/{jobID}/{jobAcct}', [QuoteordersController::class, 'getgeneralnotes'])->name('quote_orders.notes');
Route::get('/quote_orders/edit/{jobID}/{jobAcct}/{jobmod}', [QuoteordersController::class, 'edit'])->name('post.edit');
Route::get('quote_orders/products/index/{jobID}', [QuoteordersController::class, 'product'])->name('quote_orders.product');
Route::get('quote_orders/products/add/{jobID}/{jobAcct}/{Category}', [QuoteordersController::class, 'addProduct'])->name('add-product');
Route::post('quote_orders/products/search', [QuoteordersController::class, 'searchProduct'])->name('search-product');
Route::get('quote_orders/products/create/{jobID}/{product_item_id}/{productType}', [QuoteordersController::class, 'createProduct'])->name('create-product');
Route::post('quote_orders/products/store/{JobID}', [QuoteordersController::class, 'storeProduct'])->name('store-product');

Route::get('quote_orders/products/show/{jobID}/{job_product_id}', [QuoteordersController::class, 'show'])->name('show-product');
Route::post('quote_orders/products/update/{jobID}/{job_product_id}', [QuoteordersController::class, 'update'])->name('update-product');
Route::post('quote_orders/products/delete/{jobID}/{job_product_id}/{modification_id}', [QuoteordersController::class, 'deleteModification'])->name('delete-modification');

Route::post('quote_orders/products/add', [QuoteordersController::class, 'fastAdd'])->name('fastadd');
Route::get('quote_orders/products/destroy/{JobID}/{product_item_id}', [QuoteordersController::class, 'destroy'])->name('delete-product');
Route::get('quote_orders/products/copy/{jobID}/{productID}', [QuoteordersController::class, 'copy'])->name('copy-product');
Route::post('quote_orders/products/paste', [QuoteordersController::class, 'paste'])->name('paste-product');
Route::post('/quote_orders/products/line', [QuoteordersController::class, 'updateProductLine'])->name('product-line');
Route::get('/quote_orders/{JobID}/cabinet-cards', [QuoteordersController::class, 'cabinetCardsPdf'])->name('cabinet.pdf');
Route::post('quote_orders/upload', [QuoteordersController::class, 'spec_store'])->name('spec.post');
Route::post('quote_orders/save', [QuoteordersController::class, 'final_save']);
Route::get('quote_orders/delete/{id}', [QuoteordersController::class, 'upload_delete'])->name('upload-delete');
Route::get('quote_orders/generaledit/{jobID}/{jobAcct}/{id}', [QuoteordersController::class, 'upload_edit'])->name('upload-edit');
Route::post('quote_orders/autosearch', [QuoteordersController::class, 'autocompletesearch'])->name('autocomplete-search');

Route::prefix('quote_orders/construction')->group(function () {
    Route::get('/index', [QuoteordersController::class, 'consIndex'])->name('cons-first');
    Route::get('/print/{action}/{varDoor}/{varMaterial}/{varStyle}/{varFinish}/{varInside}/{varOutside}/{varCenter}/{varStile}', [QuoteordersController::class, 'pricesheetPrint'])->name('priceprint');
});
 Route::post('/quote_orders/ajaxRequest', [AjaxController::class, 'ajaxRequestPost'])->name('ajaxRequest.post');
 Route::get('/admin/reset', [PassresetController::class, 'index'])->name('reset');
 Route::post('/admin/updatepassword', [PassresetController::class, 'updatePassword'])->name('update.pass');

Route::get('/jobs', [JobsController::class, 'index']);
Route::get('/jobs/post', [JobsController::class, 'show']);
Route::post('/jobs/pdf/{jobid}', [JobsController::class, 'jobPdf']);
Route::get('/jobs/pdf/{jobid}', [JobsController::class, 'jobPdf']);
Route::get('/jobs/cancel', [JobsController::class, 'cancel']);
Route::get('/jobs/stage/{jobStage}', [JobsController::class, 'jobStage'])->name('job-stage');
Route::get('/jobs/update/{jobID}/{jobAcct}/{active}', [JobsController::class, 'update'])->name('post.update');

Route::prefix('crm')->group(function () {

    Route::get('orders', [OrdersController::class, 'inProcess']);
    Route::get('orders/all', [OrdersController::class, 'all']);
    Route::get('orders/{job_stage_slug}', [OrdersController::class, 'stage']);
    Route::get('orders/download/{job_stage_slug}', [OrdersController::class, 'download'])->name('order.download');
    Route::get('orders/{job_id}/edit', [OrdersController::class, 'editBaseOrder']);
    Route::post('orders/{job_id}/edit', [OrdersController::class, 'updateBaseOrder']);
    Route::get('orders/{job_id}/to-cv/preview', [OrdersController::class, 'toCvPreview']);
    Route::get('orders/{job_id}/to-cv/download', [OrdersController::class, 'toCvDownload']);

    Route::get('quotes', [QuotesController::class, 'index'])->name('show.index');

    Route::resource('phone-log', PhoneMessageController::class)->except([ 'destroy']);
    Route::resource('contacts', ContactsController::class);
    Route::resource('users', UsersController::class);
    Route::get('phone-log/edit/{id}', [PhoneMessageController::class, 'edit']);
});

Route::prefix('admin')->group(function () {
    Route::get('/account', [AdministrationController::class, 'getUserAccount']);
    Route::get('/account/add', [AdministrationController::class, 'accountAdd'])->name('add-account');
    Route::get('/edit-account/{id}/{page}', [AdministrationController::class, 'accountShowEdit'])->name('show-edit');
    Route::post('/account/create', [AdministrationController::class, 'accountCreate']);
    Route::get('/user/{id}/{page}', [AdministrationController::class, 'userViewEdit'])->name('view-edit');
    Route::post('/user', [AdministrationController::class, 'userUpdate'])->name('users-update');
    Route::get('users', [UsersController::class, 'index'])->name('all-users');
    Route::get('users/{id}', [UsersController::class, 'destroy'])->name('user-delete');
    Route::post('users/create', [UsersController::class, 'userStore'])->name('user-store');
});
Route::get('/news/readmore/{id}', [NewsController::class, 'getnews'])->name('readmore');
Route::prefix('download')->group(function () {
    Route::get('/', [DownloadsController::class, 'index']);
    Route::get('/show/{id}', [DownloadsController::class, 'show'])->name('downloadinfo');
    Route::get('/edit/{id}', [DownloadsController::class, 'edit'])->name('download.edit');
    Route::post('/update', [DownloadsController::class, 'update']);
    Route::get('/create', [DownloadsController::class, 'create'])->name('download.create');
    Route::post('/store', [DownloadsController::class, 'store']);
    Route::get('/destroy/{id}', [DownloadsController::class, 'destroy'])->name('download.delete');
});

Route::prefix('gallery')->group(function () {
    Route::get('/gallery', [GalleryController::class, 'index']);
    Route::get('/show', [GalleryController::class, 'subcontent']);
    Route::get('/doors', [DoorGalleryController::class, 'show']);
});

Route::prefix('tools')->group(function () {
    Route::get('/abbreviations', [ToolController::class, 'abbreviations']);
    Route::get('/download', [ToolController::class, 'downloads']);
    Route::get('/faq', [ToolController::class, 'faq']);
    Route::get('/glossary', [ToolController::class, 'glossary']);
    Route::get('/news', [ToolController::class, 'news']);
});

Route::prefix('catalog')->group(function () {
    Route::get('/', [CatalogController::class, 'index']);
    Route::get('/generate', [CatalogController::class, 'generate']);
    Route::get('/ord', [CatalogController::class, 'ord']);
});

Route::prefix('administration')->group(function () {
    Route::get('/', [AdministrationController::class, 'index']);

resources/views/admin/account.blade.php
@extends('templates.crm')

@section('content')


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-UX">
            <div class="panel-heading">Settings</div>           
            <div class="panel-body">
                <div class="row content-header "> <h2 class="bottom_line">Account</h2></div>
                <div class="content-body">
                    <div class="row">
                    <a href="{{route('add-account')}}"> <button type="button" class="btn btn-success add_btn"><i class="glyphicon glyphicon-plus-sign"></i>Add</button></a>
                    </div>
                    <table id="table" class="table table-striped table-responsive table-bordered dataTable no-footer"  role="grid" aria-describedby="table_info" cellspacing="0">
                        <thead>
                            <tr>
                                <th class="text-left">Company Name</th>
                                <th class="text-left">X Discount</th>
                                <th class="text-right">Show in Door Builder</th>
                                <th class="text-right">Active</th>
                                <th class="text-left">Potential</th>
                                <th class="dt-center"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($accounts as $row)
                            <tr class="" role="row" >
                                <td class="text-left" > {{ $row->Name }}</td>
                                <td class="text-left"> {{ $row->MultiplierDiscount }}{{$row->LastName}}</td>
                                @if($row->show_in_door_builder == 0)
                                    <td class="text-center" style="background-color: #c12e2a; color:white "> No</td>
                                @else
                                    <td class="text-center" style="background-color: #419641; color:white "> Yes</td>
                                @endif
                                @if($row->Active == 0)
                                    <td class="text-center" style="background-color: #c12e2a; color:white "> No</td>
                                @else
                                    <td class="text-center" style="background-color: #419641; color:white "> Yes</td>
                                @endif
                                @if($row->potential == 0)
                                    <td class="text-center" style="background-color:#419641; color:white "> No</td>
                                @else
                                    <td class="text-center" style="background-color:#F69231; color:white "> Yes</td>
                                @endif
                                <td class="text-center"> 
                                    <span class="btn-group">
                                        <a class="btn btn-sm btn-info"  href="{{route('show-edit',['id'=>$row->ID,'page'=>'view'])}}"><i class="glyphicon glyphicon-search"></i></a>
                                        <a class="btn btn-sm btn-warning" href="{{route('show-edit',['id'=>$row->ID,'page'=>'edit'])}}"><i class="glyphicon glyphicon-edit"></i></a>
                                    </span>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



@stop


@section('scripts')

<script>
$(document).ready(function() {
    $('#table').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'print',
            'csv'
        ],
        "pageLength": 1000,
        "columnDefs": [
            {
                "targets": [ 5 ],
                "orderable": false,
                "searchable": false
            }
        ]
    })
      
});

</script>

@stop


@section('styles')
<style>
    .content-header{
        padding: 0px 15px;
    }
    .bottom_line{
        border-bottom: 1px solid #ddd;
    }
    .add_btn{
        margin-left: 15px;
    }
    .pull-right{
        margin-top: 10px;
        margin-right: 15px;
    }
    #table{
        border-top: 1px solid rgb(175, 169, 169);
        font-size: 14px;
    }
</style>
@stop

resources/views/admin/add-account.blade.php
@extends('templates.crm')

@section('content')

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-UX">
            <div class="panel-heading">Settings</div>           
            <div class="panel-body">
                <div class="row "> <h2 class="bottom_line">Account<span class="subpage"> - {{ $page}}</span></h2></div>
                {{ Form::open(['method'=>'post', 'class'=>'form-horizontal', 'url'=>"admin/account/create"]) }}
                    {{Form::hidden('act','accountCreate')}}
                    <div class="row">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-danger add_cancel"></i>Cancel</button>
                            <button type="submit" class="btn btn-success add_btn"></i>Save</button>
                        </div>
                    </div>
                
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#account">Account Info</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="account">

                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">Company Name</label>
                                <div class="col-sm-9">
                                    {{ Form::text('CompanyName','', array('class'=>'form-control')) }}   
                                    @php echo html_entity_decode($errors->first('CompanyName', '<br><p class="text-danger">:message</p>')); @endphp                       
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">Address</label>
                                <div class="col-sm-9">
                                    {{ Form::text('Address','',  array('class'=>'form-control')) }}                          
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">Address</label>
                                <div class="col-sm-9">
                                    {{ Form::text('Address2','',  array('class'=>'form-control')) }}                         
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">City</label>
                                <div class="col-sm-9">
                                    {{ Form::text('City','', array('class'=>'form-control')) }}                          
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">State</label>
                                <div class="col-sm-9">
                                    {{ Form::text('State','',  array('class'=>'form-control')) }}                          
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">Zip</label>
                                <div class="col-sm-9">
                                    {{ Form::text('Zip','', array('class'=>'form-control')) }}                          
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">Phone</label>
                                <div class="col-sm-9">
                                    {{ Form::text('Phone','',  array('class'=>'form-control')) }}                         
                                </div>
                            </div>
                        
                            <div class="form-group">
                                <label for="CreatedDate" class="col-sm-3 control-label">X Discount</label>
                                <div class="col-sm-9">
                                    {{ Form::text('XDiscount','',  array('class'=>'form-control','data-pattern'=>'numeric')) }}
                                    @php echo html_entity_decode($errors->first('XDiscount', '<br><p class="text-danger">:message</p>')); @endphp                           
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="Account" class="col-sm-3 control-label">Brands</label>
                                <div class="col-sm-9">
                                    {{ Form::select('brand', array('' => '-none-', '1' => 'Imperia', '2' => 'NKD-JJ',  '3' => 'PureKinchen-JJ'), '',array('class'=>'form-control','size'=>10)) }}
                                    @php echo html_entity_decode($errors->first('brand', '<br><p class="text-danger">:message</p>')); @endphp
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Account" class="col-sm-3 control-label">Default Brand</label>
                                <div class="col-sm-9">
                                    {{ Form::select('defaultbrand', array('' => '-none-', '1' => 'Imperia', '2' => 'NKD-JJ',  '3' => 'PureKinchen-JJ'), '1',array('class'=>'form-control')) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Account" class="col-sm-3 control-label">Show IN Door Builder</label>
                                <div class="col-sm-9 custom_check">
                                    {{ Form::checkbox('builder',1,true) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Account" class="col-sm-3 control-label">Active</label>
                                <div class="col-sm-9 custom_check">
                                    {{ Form::checkbox('active', 1, true) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Account" class="col-sm-3 control-label">Portential</label>
                                <div class="col-sm-9 custom_check">
                                    {{ Form::checkbox('potential', 1, false) }}
                                </div>
                            </div>
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>



@stop


@section('scripts')

<script>
$(document).ready(function() {
    $('.nav-tabs a').click(function(){
        $(this).tab('show');
    });
    $('.nav-tabs a[href="#account"]').tab('show');
    $('.nav-tabs a:first').tab('show');
    $('.nav-tabs a:last').tab('show'); 
    $('.add_cancel').click(function(){
        window.history.back();
    });
});


</script>

@stop


@section('styles')
<style>
    .content-header{
        padding: 0px 15px;
        
    }
    .bottom_line{
        float: left;
        border-bottom: 1px solid #ddd;
        width: 97%;
        margin-left: 15px;
        
    }
    .add_btn{
        margin-left: 15px;
    }
    .pull-right{
        margin-top: 10px;
        margin-right: 15px;
    }

    .subpage { 
        font-size:0.6em; 
    }
    
    .custom_check{
        margin-top: 7px;
    }

    .tab-content{
        box-shadow: 0 1px 1px 1px gray;
        padding: 20px;
    }
    .add_cancel{
        margin-top: 10px;
    }
</style>
@stop

resources/views/admin/index.blade.php
@extends('templates.crm')

@section('content')


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-UX">
            <div class="panel-heading">Settings</div>           
            <div class="panel-body">
                <div class="row content-header "> <h2 class="bottom_line">Users</h2></div>
                <div class="content-body">
                    <div class="row">
                    <a href="{{route('users.create')}}"> <button type="button" class="btn btn-success add_btn"><i class="glyphicon glyphicon-plus-sign"></i>Add</button></a>
                    </div>
                    <table id="table" class="table table-striped table-responsive table-bordered dataTable no-footer"  role="grid" aria-describedby="table_info" cellspacing="0">
                        <thead class="account_view">
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-left" >Username</th>
                                <th class="text-left" >First Name</th>
                                <th class="text-left">Last Name</th>
                                <th class="text-left">Email</th>
                                {{-- <th class="dt-left">X Customer</th> --}}
                                <th class="dt-left" style="width: 120px;">Receive DYOD Emails</th>
                                <th class="dt-left">Active</th>
                                <th class="text-left" > </th>
                            </tr>
                        @if(count($users))
                        <?php //dd($users);?>
                        <tbody>
                            @php $i = 1; @endphp
                            @foreach($users as $row)                                
                            <tr>
                                <td class="text-center">{{$i++}}</td>
                                <td class="text-left">{{$row->Username}}</td>
                                <td class="text-left">{{$row->FirstName}}</td>
                                <td class="text-left">{{$row->LastName}}</td>
                                <td class="text-left">{{$row->Email}}</td>
                                <td class="text-left">{{$row->MultiplierCustomer}}</td>
                                @if($row->receive_door_spec_emails == 1)
                                <td class="text-left"> Yes</td>
                                @else
                                <td class="text-left"> No</td>
                                @endif
                                @if($row->Active == 1)
                                <td class="text-center" style="background-color: #419641; color:white"> Yes</td>
                                @else
                                <td class="text-center" style="background-color: #c12e2a; color:white"> No</td>
                                @endif
                                <td class="text-center" style="width: 110px;padding:5px;">
                                    <span class="btn-group">
                                        <a class="btn btn-sm btn-info "  href="{{route('view-edit',['id'=>$row->UserID,'page'=>'view'])}}" ><i class="glyphicon glyphicon-search"></i></a>
                                        <a class="btn btn-sm btn-warning" href="{{route('view-edit',['id'=>$row->UserID,'page'=>'edit'])}}"><i class="glyphicon glyphicon-edit"></i></a>
                                        <a class="btn btn-sm btn-danger user_delete" href="{{route('user-delete', ['id'=>$row->UserID]) }}" onclick="return confirm('Do you really want remove this user entry?') "><i class="glyphicon glyphicon-remove"></i></a>                                               
                                    </span>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        @endif
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



@stop


@section('scripts')

<script>
$(document).ready(function() {
    $('#table').DataTable({
        ordering : false ,
        dom: 'Bfrtip',
        buttons: [
            'print',
            'csv'
        ],   
        "pageLength": 1000,    
    });
      
});

</script>

@stop


@section('styles')
<style>
    .content-header{
        padding: 0px 15px;
    }
    .bottom_line{
        border-bottom: 1px solid #ddd;
    }
    .add_btn{
        margin-left: 15px;
    }
    .pull-right{
        margin-top: 10px;
        margin-right: 15px;
    }
    #table{
        border-top: 1px solid rgb(175, 169, 169);
        font-size: 14px;
    }
    table.dataTable thead th{
        padding:5px;
    }
</style>
@stop

resources/views/admin/reset.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{config('app.name')}}  Password Reset</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/custom.css?n=1" media="screen') }}">
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Reset Password') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{route('update.pass')}}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">
                                @php echo html_entity_decode($errors->first('email', '<br><p class="text-danger">:message</p>')); @endphp
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Old Password') }}</label>

                            <div class="col-md-6">
                                <input id="oldpassword" type="password" class="form-control " name="oldpassword" required autocomplete="old-password">
                                @php echo html_entity_decode($errors->first('oldpassword', '<br><p class="text-danger">:message</p>')); @endphp
                      
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('New Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required autocomplete="password">
                                @php echo html_entity_decode($errors->first('password', '<br><p class="text-danger">:message</p>')); @endphp
                    
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="password">
                                @php echo html_entity_decode($errors->first('password_confirmation', '<br><p class="text-danger">:message</p>')); @endphp
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                                <a href="{{ route('home')}} " style="float:right"><button type="button" class="btn btn-primary">
                                    {{ __('Cancel') }}
                                </button></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>